Close reasons
Teamwork/websocket-json-stream pull request #1
Opened 2018-07-25 05:18 UTC by nateps

Add support for differentiating between different types of WebSocket closures by passing `code` and `reason` values to `ws.close()`. This is helpful, because a client may wish to perform different reconnection logic depending on the reason for disconnection.

In particular, it is useful to be able to differentiate intentional disconnections where the server wishes to indicate to the client that it should not reconnect at all or the client should delay for a more extended time before it reconnects. If, for example, a client's application version is no longer supported, the server may wish to disconnect with a reason that indicates the client should not attempt reconnection and it should refresh or update its code first.

In addition, this PR includes a full shim of Node's `stream.destroy()`, borrowed from current master of Node. The minimal shim was not consistent with the current implementation of stream.destroy() in Node 8+, particularly because it didn't emit passed in errors as an 'error' event. If we're shimming this, I believe we should use the full implementation from current Node for more consistency in API.

Including a shim of `stream.destroy()` is a key part of this PR, since it now produces a different close code than `stream.end()`

2018-07-25 09:12 UTC, gkubisa requested changes
Looks great to me! Thanks @nateps :+1:

Could you just make the few little changes before I merge, please?

2018-07-25 09:12 UTC, gkubisa commented on test/close-status.js
> +    it('should emit CloseEvent with code 1000 and reason "stream end" on clientStream.end()', function (done) {
Great tests!

Could we also get the same set of tests where the `close` event listener is attached to `this.serverWebSocket`? It's just to make sure that the server also gets the code and reason as expected.

And for consistency, could we change `.onclose = ...` to `.on('close', ...)`?

2018-07-25 09:12 UTC, gkubisa commented on destroy.js
> +// Copied from:
As this code has been copied and pasted from node, I don't think we need test coverage on it. Please add `/* istanbul ignore file */` at the top of this file.

2018-07-25 18:18 UTC, nateps commented on test/close-status.js
> +    it('should emit CloseEvent with code 1000 and reason "stream end" on clientStream.end()', function (done) {
Good points. I updated to run all tests against both `this.clientWebSocket` and `this.serverWebSocket`.

In regard to the close listener, these actually are different. `ws` emits a Node.js-style `on('close', ...)` event that has different arguments than the standard event interface of WebSockets. The WebSocket `CloseEvent` is emitted if you use `addEventListener('close', ...)` or `onclose = `. I decided to add tests for both.

2018-07-25 18:21 UTC, nateps commented on destroy.js
> +// Copied from:
Agreed. I see mention of `/* istanbul ignore file */`, but it didn't seem to work (adding did not change coverage appropriately). I wonder if it is actually supported?

I used `/* istanbul ignore next */` before each function instead.

2018-07-25 18:37 UTC, nateps commented
Regarding coverage testing, Coveralls is not reporting the same output as Istanbul anymore. They made some changes in Coveralls 3.0, and branch coverage is computed within ignored statements.

See output from Travis build showing coverage (with ignores) is 100%: https://travis-ci.org/Teamwork/websocket-json-stream/jobs/408183093

Apparently this can be worked around by downgrading the version of coveralls or by turning off the branch coverage setting for the repo:
https://github.com/lemurheavy/coveralls-public/issues/939
https://github.com/nickmerwin/node-coveralls/issues/158#issuecomment-286318287

2018-07-26 11:51 UTC, gkubisa commented on destroy.js
> +// Copied from:
No problem, I excluded that file on the command line using the `-x` flag.

2018-07-26 11:52 UTC, gkubisa approved these changes
Everything is in order now. Thanks for the excellent contribution :boom:

2018-07-26 11:59 UTC, merged

2018-07-26 20:41 UTC, nateps commented
Awesome. Thanks for the review!

On Thu, Jul 26, 2018 at 4:59 AM, Greg Kubisa <notifications@github.com>
wrote:

> Merged #1 <https://github.com/Teamwork/websocket-json-stream/pull/1>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Teamwork/websocket-json-stream/pull/1#event-1754835341>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAOLNCPhXMTob7cxyfHMjr1DCOBKIq5nks5uKa8pgaJpZM4VfcrQ>
> .
>